default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Figaro.env.postgresql_username %>
  password: <%= Figaro.env.postgresql_password %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Figaro.env.postgresql_database_development %>

production:
  <<: *default
  database: <%= Figaro.env.postgresql_database_production %>
